"""Add role column to messages

Revision ID: 15978ec8d79b
Revises: 20250514_fts_message_content
Create Date: 2025-05-19 07:44:10.898435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15978ec8d79b'
down_revision: Union[str, None] = '20250514_fts_message_content'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column with a default value
    op.add_column('messages', sa.Column('role', sa.String(length=20), nullable=True))
    # Update existing rows with a default role
    op.execute("UPDATE messages SET role = 'user' WHERE role IS NULL")
    # Now make the column NOT NULL
    op.alter_column('messages', 'role', nullable=False)
    op.drop_index('ix_messages_content_tsv', table_name='messages', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_content_tsv', 'messages', ['content_tsv'], unique=False, postgresql_using='gin')
    op.drop_column('messages', 'role')
    # ### end Alembic commands ###
